### PR TITLE
feat: added getSessionId, startSession, endSession method

### PR DESCRIPTION
**Pull request by numandev1**
## Description of the change

Please review after these two android ios PR merged
https://github.com/rudderlabs/rudder-sdk-ios/pull/324
https://github.com/rudderlabs/rudder-sdk-android/pull/220

before merge these two PRs, you can apply these two patches and test
### Android
```
implementation 'com.github.numandev1:rudder-sdk-android:develop-SNAPSHOT'
```
### IOS
`ios/patches/Rudder+1.14.0.diff`
```
diff --git a/cocoapods-patch-20230515-61514-sfxg4s/Rudder/Sources/Classes/Headers/Public/RSClient.h b/Pods/Rudder/Sources/Classes/Headers/Public/RSClient.h
index 54f84f5..d971478 100644
--- a/cocoapods-patch-20230515-61514-sfxg4s/Rudder/Sources/Classes/Headers/Public/RSClient.h
+++ b/Pods/Rudder/Sources/Classes/Headers/Public/RSClient.h
@@ -87,6 +87,7 @@ NS_ASSUME_NONNULL_BEGIN
 - (void)startSession;
 - (void)startSession:(long)sessionId;
 - (void)endSession;
+- (NSString*)getSessionId;

 @end

diff --git a/cocoapods-patch-20230515-61514-sfxg4s/Rudder/Sources/Classes/RSClient.m b/Pods/Rudder/Sources/Classes/RSClient.m
index 2c14592..ca618f1 100644
--- a/cocoapods-patch-20230515-61514-sfxg4s/Rudder/Sources/Classes/RSClient.m
+++ b/Pods/Rudder/Sources/Classes/RSClient.m
@@ -18,6 +18,7 @@ static RSEventRepository *_repository = nil;
 static RSUserSession *_userSession = nil;
 static RSOption* _defaultOptions = nil;
 static NSString* _deviceToken = nil;
+static long currentSessionId = -1;

 @implementation RSClient

@@ -444,14 +445,24 @@ static NSString* _deviceToken = nil;
         return;
     }
     if(_repository != nil) {
+        currentSessionId = sessionId;
         [_repository startSession:sessionId];
     }
 }

 - (void)endSession {
     if(_repository != nil) {
+        currentSessionId=-1;
         [_repository endSession];
     }
 }

+- (NSString*)getSessionId {
+    if (currentSessionId == -1) {
+        return nil;
+    } else {
+        return [NSString stringWithFormat:@"%ld", currentSessionId];
+    }
+}
+
 @end

```

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

https://www.rudderstack.com/docs/sources/event-streams/sdks/session-tracking/#getting-session-id-for-javascript-sdk

### Development

- [X] Lint rules pass locally
- [X] The code changed/added as part of this pull request has been covered with tests
- [X] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by 1abhishekpandey** [comment]
Hey @numandev1, thanks for this contribution we are really looking forward to introducing the session tracking features in React-Native. We are going to pick up this item soon.

At the moment the changes you have made are mainly containing two things:
1. Manual session tracking
2. getSessionId API

But we also wanted to bring automatic session tracking capability. We will keep you updated.

**Comment by rtol5** [comment]
hi there – is still PR still being worked on? would love to have session tracking enabled on React Native 🥺

**Comment by 1abhishekpandey** [comment]
Due to other higher-priority tasks, we are currently unable to work on this. However, we have plans to pick this item in the next sprint.

**Comment by 1abhishekpandey** [comment]
Closing this PR since development work is being continued in another [PR](https://github.com/rudderlabs/rudder-sdk-react-native/pull/227).
`getSessionId()` API will be implemented in future.

**Comment by 1abhishekpandey** [comment]
Hey @numandev1,
We've launched the React Native SDK version [1.8.0](https://github.com/rudderlabs/rudder-sdk-react-native/releases/tag/rudder-sdk-react-native%401.8.0) with the session tracking feature. Please utilize this version to access the session tracking feature.
For more info, refer to our doc:
1. https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-react-native-sdk/#tracking-user-sessions
2. https://www.rudderstack.com/docs/sources/event-streams/sdks/session-tracking/

**Pull request closed without merging**
